sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer install
  - ./vendor/bin/phpcs --config-set installed_paths /home/travis/build/SIWECOS/siwecos-wordpress/vendor/wp-coding-standards/wpcs

script:
  - ./vendor/bin/phpcs --standard=WordPress-Core siwecos.php lib/*.php output/*.php
