sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer install
  - ./vendor/bin/phpcs --config-set installed_paths ./vendor/wp-coding/standards/wpcs

script:
  - phpcs --standard=WordPress-Core *.php **/*.php
